#!/bin/sh
set -e

export NOMAD_SHARE_DIR="${SYNOPKG_PKGDEST_VOL}/nomad"

mkdir -p /var/packages/nomad/var
cat <<EOF > "/var/packages/nomad/var/env.sh"
export NOMAD_SHARE_DIR="$NOMAD_SHARE_DIR"
EOF

mkdir -p "${NOMAD_SHARE_DIR}/etc/nomad.d"
if [ ! -f "${NOMAD_SHARE_DIR}/etc/nomad.d/nomad.hcl" ]; then
  mkdir -p "${NOMAD_SHARE_DIR}/var/lib/nomad"
  cat <<EOF > "${NOMAD_SHARE_DIR}/etc/nomad.d/nomad.hcl"
data_dir="${NOMAD_SHARE_DIR}/var/lib/nomad"
server {
  enabled = true
  bootstrap_expect = 1
}
client {
  enabled = true
}
plugin "docker" {
  config {
    allow_privileged = true
    volumes {
      # required for bind mounting host directories
      enabled = true
    }
  }
}
EOF
fi;

exit 0
