#!/bin/sh

SERVICE_NAME="${SYNOPKG_PKGNAME}"
NOMAD_SHARE_DIR="${SYNOPKG_PKGDEST_VOL}/nomad"
PID_FILE="${SYNOPKG_PKGVAR}/nomad.pid"
LOG_FILE="${SYNOPKG_PKGVAR}/nomad.stdout.log"
SERVICE_COMMAND="/usr/local/bin/nomad agent -config ${NOMAD_SHARE_DIR}/etc/nomad.d/nomad.hcl"

start_daemon() {
    local ts=$(date --iso-8601=second)
    echo "${ts} Starting ${SERVICE_NAME} with: ${SERVICE_COMMAND}" >${LOG_FILE}
    ${SERVICE_COMMAND} >>${LOG_FILE} 2>&1 &
    echo "$!" >"${PID_FILE}"
}

stop_daemon() {
    if [ -r "${PID_FILE}" ]; then
        local PID=$(cat "${PID_FILE}")
        local ts=$(date --iso-8601=second)
        echo "${ts} Stopping ${SERVICE_NAME} service PID=${PID}" >>${LOG_FILE}
        kill -TERM $PID >>${LOG_FILE} 2>&1
        wait_for_status 1 || kill -KILL $PID >>${LOG_FILE} 2>&1
        rm -f "${PID_FILE}" >/dev/null
    fi
}

daemon_status() {
    if [ -r "${PID_FILE}" ]; then
        local PID=$(cat "${PID_FILE}")
        if ps -o pid -p ${PID} > /dev/null; then
            return
        fi
        rm -f "${PID_FILE}" >/dev/null
    fi
    return 1
}

case $1 in
	start)
		if daemon_status; then
			exit 0
		else
			start_daemon
			exit $?
		fi
	;;
	stop)
		if daemon_status; then
			stop_daemon
			exit $?
		else
			exit 0
		fi
	;;
	status)
		if daemon_status; then
			echo "${SERVICE_NAME} is running"
			exit 0
		else
			echo "${SERVICE_NAME} is not running"
			exit 3
		fi
	;;
	log)
		exit 0
	;;
	*)
		echo "Usage: $0 {start|stop|status}" >&2
		exit 1
	;;
esac
