#!/bin/bash
case "$1" in
    start)
        if [ "${EUID}" -eq 0 ]; then
            sudo -u nomad synosystemctl start pkguser-nomad
        else
            synosystemctl start pkguser-nomad
        fi
        ;;
    stop)
        if [ "${EUID}" -eq 0 ]; then
            sudo -u nomad synosystemctl stop pkguser-nomad
        else
            synosystemctl stop pkguser-nomad
        fi
        ;;
    status)
        if [ "${EUID}" -eq 0 ]; then
            sudo -u nomad synosystemctl get-active-status pkguser-nomad
        else
            synosystemctl get-active-status pkguser-nomad
        fi
        ;;
    log)
        echo ""
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 1
        ;;
esac
